MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.10.03

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,39 +4,62 @@
 language: generic
 
 os: osx
-osx_image: beta-xcode6.1
+osx_image: xcode6.4
 
 env:
   matrix:
-    
-    - CONDA_PY=27
-    - CONDA_PY=34
-    - CONDA_PY=35
+    - CONFIG=osx_python2.7
+    - CONFIG=osx_python3.6
+    - CONFIG=osx_python3.7
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "TqIkkMvUX1V/DvHKWX8TeDt3JR7DTxLVMeupTjZhzWJEe3gLkTU+gjZkQPey+jxzT95fP/B9kBCIxBA1d5RSNjujZrDdfaIJUQBKLILXZQt7NaOerTuBXcfqLwlDnx/TgpeO4J08sBoDfs1VMFQvAj0O0ehKeTCl6dxM2mDQyyjE8WDhts97E72xFdnzUXSssFbV2aqSrePEcJDjAioTMygzt9h85C9VSnwSHd3SrGIZWfRDgwvW+uNsJgAbZfECgxrAsvwDMgCQnlHJS5J3OCbN+D8sxARbw3w52MKXJ3k/S2I+el/wk3efwGw76Z5FdvR0/axNRq9mn5sH+1HDT+yry3DM1KJulvBCgDu0S7HgD+flHZRSLZZ7+Z4xfEUtuhsW8gM904SuZhCP+bWJ6z5+wX58r9Uyl3Ok5XSrZsVoQ7SwSXiM1LluXEqN5zsU5pvWaaDvBkmfHIQEzl3MsdVbJWhqv466J7OV/VY9Po56dnwEqeTC7r6hgFJYufGzxsfiAUJpiWymBlBurxYRV75K44M3aVYUTZaSQl74DDrDh7mJCcQWbSd89wqT5AsNwLQykwL1laSGEaJhB3Ucmsw6bmU5lB1nJuZH5X9N2dROXVr/q6JH06yKNOx7J+RD+U8Bmur4wAOEelE2dE8hnecwu3FatmZpUxW3uC3UaPw="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
+      echo ""
+      echo "Installing a fresh version of Miniconda."
       MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
       curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
